### ISSUE TITLE
Service open_orchestra_api.oauth2.strategy.client_credentials_grant

### ISSUE THREAD

**Issue by itkg-bfouche** [open-orchestra/open-orchestra-base-api-bundle#7]
The service open_orchestra_api.oauth2.strategy.clie nt_credentials_grant is dependent on UserBundle because of the argument %open_orchestra_user.document.access_to ken.class %.

**Comment by nicolasThal** [comment]
https://github.com/open-orchestra/open-orchestra-base-api-bundle/pull/8
https://github.com/open-orchestra/open-orchestra-user-bundle/pull/52
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/782

This issue will be solved in the 0.2.4 tag
